modLoader = "javafml"
loaderVersion = "[40,)"
issueTrackerURL = "https://github.com/NMagpie/TFC-IE-Crossover/issues"
license = "MIT"

[[mods]]
modId = "tfc_ie_addon"
version = "${file.jarVersion}"
displayName = "TFC + IE Crossover"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/tfc-ie-crossover"
logoFile = "logo.png"
credits = "Thanks to Developers of such wonderful mods as TerraFirmaCraft: TNG and Immersive Engineering.\nEspecially to EERussianguy, whose addon FirmaLife was used as base for this addon.\nSome textures of BluSunrize were used or modified.\nAlso, were used some textures from TFC: TNG, all credits to the developers."
authors = "NMagpie and maintained by HermitOwO"
description = "Addon that makes TFC and IE compatible."
updateJSONURL = "https://raw.githubusercontent.com/NMagpie/TFC-IE-Crossover/1.18.x/update.json"

[[dependencies.tfc_ie_addon]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.tfc_ie_addon]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,1.19)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.tfc_ie_addon]]
modId = "tfc"
mandatory = true
versionRange = "[1.18.2-2.2.3,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.tfc_ie_addon]]
modId = "immersiveengineering"
mandatory = true
versionRange = "[1.18.2-8.4.0-161,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.tfc_ie_addon]]
modId = "immersivepetroleum"
mandatory = false
versionRange = "[1.18.2-4.1.0-21,)"
ordering = "AFTER"
side = "BOTH"